#!/usr/bin/env bash

declare -x MEMCACHED_MAXMEM
: "${MEMCACHED_MAXMEM:="64"}"

declare -x MEMCACHED_MAXCONN
: "${MEMCACHED_MAXCONN:="1024"}"

declare -x MEMCACHED_THREADS
: "${MEMCACHED_THREADS:="4"}"

declare -x MEMCACHED_OPTS
: "${MEMCACHED_OPTS:=""}"

declare -x MEMCACHED_SKIP_CHOWN
: "${MEMCACHED_SKIP_CHOWN:="false"}"
