FROM webhippie/alpine:latest-arm64@sha256:d059dc58e0739aac431b71e85cde3fd0ebdafd6d57f51113647548c15eff5ea0

VOLUME ["/var/lib/memcached"]
EXPOSE 11211

WORKDIR /var/lib/memcached
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/memcached && \
  groupadd -g 1000 memcached && \
  useradd -u 1000 -d /var/lib/memcached -g memcached -s /bin/bash -m memcached && \
  apk add memcached libmemcached && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
