FROM webhippie/alpine:latest-arm@sha256:3e3cc7a798fc86f8845422f425d1f0aff996be568eacb33fd1a7b921ba2ee799

VOLUME ["/var/lib/memcached"]
EXPOSE 11211

WORKDIR /var/lib/memcached
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/memcached && \
  groupadd -g 1000 memcached && \
  useradd -u 1000 -d /var/lib/memcached -g memcached -s /bin/bash -m memcached && \
  apk add memcached libmemcached && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
