FROM webhippie/alpine:latest-arm64@sha256:c68c53afbd4d681569437fd83475f9e5e84350bada9ea53cc01bfb0798d41ba8

VOLUME ["/var/lib/memcached"]
EXPOSE 11211

WORKDIR /var/lib/memcached
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/memcached && \
  groupadd -g 1000 memcached && \
  useradd -u 1000 -d /var/lib/memcached -g memcached -s /bin/bash -m memcached && \
  apk add memcached libmemcached && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
