FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:d1eb4dd457e2faee45d8ee186148631443cbbf65f00979de7a9663f4b91ab046

VOLUME ["/var/lib/memcached"]
EXPOSE 11211

WORKDIR /var/lib/memcached
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/memcached && \
  groupadd -g 1000 memcached && \
  useradd -u 1000 -d /var/lib/memcached -g memcached -s /bin/bash -m memcached && \
  apk add memcached libmemcached && \
  rm -rf /var/cache/apk/*

COPY ./overlay /
