FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:bb898471112353d7f3d95cf679e3a301657687dae02a3ac8ad40246c6d5342de

VOLUME ["/var/lib/memcached"]
EXPOSE 11211

WORKDIR /var/lib/memcached
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/memcached && \
  groupadd -g 1000 memcached && \
  useradd -u 1000 -d /var/lib/memcached -g memcached -s /bin/bash -m memcached && \
  apk add memcached libmemcached && \
  rm -rf /var/cache/apk/*

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
