#!/usr/bin/env bash
# Usage: manage start
# Summary: Start the Memcached server
# Help: This command is used to really start the Memcached server process.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

if manage-running
then
  echo "Server is already running"
else
  manage-prepare && /usr/bin/memcached -vv -u memcached -l 0.0.0.0 -m ${MEMCACHED_MAXMEM} -c ${MEMCACHED_MAXCONN} -t ${MEMCACHED_THREADS}
fi
