#!/usr/bin/env bash
# Usage: manage pid
# Summary: Return the process id of Memcached
# Help: This command is used to gather the process id of the Memcached server.
set -e
[[ -z $_MANAGE_ROOT ]] && exit 1

pgrep -f memcached
